name: Create Resources

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Source Environment Variables
        run: |
          source .github/workflows/env.sh
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
        shell: bash

      - name: Debug Environment Variables
        run: |
          echo "S3_BUCKET=${S3_BUCKET}"
          echo "AWS_REGION=${AWS_REGION}"

      - name: Extract Project Name
        run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="key=${PROJECT_NAME}/terraform.tfstate" \
            -backend-config="bucket=${S3_BUCKET}" \
            -backend-config="region=${AWS_REGION}"
        working-directory: ./terraform

      - name: Validate Terraform Configuration
        run: terraform validate
        working-directory: ./terraform

      - name: Plan Terraform Deployment
        run: terraform plan -out=terraform.plan
        working-directory: ./terraform

      - name: Apply Terraform to create resources
        run: terraform apply -auto-approve terraform.plan
        working-directory: ./terraform

      - name: Output and Print API Endpoint
        run: |
          API_ENDPOINT=$(terraform output -raw api_endpoint)
          echo "API Endpoint: ${API_ENDPOINT}"
        working-directory: ./terraform
