name: Create Resources

on:
  workflow_dispatch:

jobs:
  setup_env:
    uses: ./.github/workflows/setup-env.yml

  create:
    needs: setup_env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Debugging
        run: |
          echo "AWS_REGION: ${{ env.AWS_REGION }}"
          echo "S3_BUCKET: ${{ needs.setup_env.outputs.S3_BUCKET }}"
          echo "S3_KEY_PATH: ${{ needs.setup_env.outputs.S3_KEY_PATH }}"

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="key=${{ needs.setup_env.outputs.S3_KEY_PATH }}/terraform.tfstate" \
            -backend-config="bucket=${{ needs.setup_env.outputs.S3_BUCKET }}" \
            -backend-config="region=${{ env.AWS_REGION }}"  \
            -input=false
        working-directory: ./terraform

      - name: Apply Terraform to create resources
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Save API Endpoint to S3
        run: |
          echo $API_ENDPOINT > api_endpoint.txt
          aws s3 cp api_endpoint.txt s3://${{ needs.setup_env.outputs.S3_BUCKET }}/${{ needs.setup_env.outputs.S3_KEY_PATH }}/api_endpoint.txt
