jobs:
  create:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Source Environment Variables from env.sh
        run: |
          source .github/workflows/env.sh
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
        shell: bash

      - name: Extract Project Name
        run: |
          PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "PROJECT_NAME=${PROJECT_NAME}"
          echo "S3_BUCKET=${S3_BUCKET}"
          echo "AWS_REGION=${AWS_REGION}"

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="key=${PROJECT_NAME}/terraform.tfstate" \
            -backend-config="bucket=${S3_BUCKET}" \
            -backend-config="region=${AWS_REGION}"
        shell: /usr/bin/bash -e {0}
