name: Delete Resources

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Extract Project Name
        run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="key=${PROJECT_NAME}/terraform.tfstate" \
            -backend-config="bucket=glpi-bedrock-project-terraform-state" \
            -backend-config="region=${AWS_REGION}"
        working-directory: ./terraform

      - name: Destroy Resources
        run: terraform destroy -auto-approve
        working-directory: ./terraform
