name: Deploy and Test AWS Lambda (Python)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp -r ./src/* ./package/ || echo "No src directory, skipping"
          cd package
          zip -r ../function.zip .
          cd ..

      - name: Deploy Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name lambda_function_bedrock \
            --zip-file fileb://function.zip \
            --region us-east-1 \
            --debug 2>&1 | tee debug.log
          echo "Debug log:"
          cat debug.log

  test:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Integration Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Running integration test..."
          aws lambda invoke \
            --function-name lambda_function_bedrock \
            --payload '{\"body\": \"{\\\"model_id\\\": \\\"meta.llama3-70b-instruct-v1:0\\\", \\\"params\\\": {\\\"prompt\\\": \\\"Integration test prompt\\\", \\\"max_gen_len\\\": 512, \\\"temperature\\\": 0.7, \\\"top_p\\\": 0.9}}\"}' \
            --log-type Tail \
            --region us-east-1 \
            output_test.txt 2> error_test.log | tee result_test.log

          if [ -s result_test.log ]; then
            echo "Integration test passed!"
            echo "output_text.txt content"
            cat output_test.txt
            echo "result_test.log content"
            cat result_test.log
          else
            echo "Integration test failed. No result_test.log produced."
            echo "output_text.txt content"
            cat output_test.txt
            echo "result_test.log content"
            cat result_test.log
            echo "error_test.log content"
            cat error_test.log
            
            exit 1
          fi
