name: Deploy and Test AWS Lambda (Python)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Source Environment Variables
        run: |
          source .github/workflows/env.sh
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
        shell: bash

      - name: Debug Environment Variables
        run: |
          echo "S3_BUCKET=${S3_BUCKET}"
          echo "AWS_REGION=${AWS_REGION}"

      - name: Extract Project Name
        run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp -r ./src/* ./package/ || echo "No src directory, skipping"
          cd package
          zip -r ../function.zip .
          cd ..

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name $PROJECT_NAME \
            --zip-file fileb://function.zip \
            --region $AWS_REGION \
            --debug 2>&1 | tee debug.log
          echo "Debug log:"
          cat debug.log

  test:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the Python version your script requires

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Retrieve API Endpoint from S3
        run: |
          aws s3 cp s3://${S3_BUCKET}/${S3_KEY_PATH}/api_endpoint.txt .
          if [ -f api_endpoint.txt ]; then
            echo "API_ENDPOINT=$(cat api_endpoint.txt)" >> $GITHUB_ENV
          else
            echo "Error: API endpoint file not found" >&2
            exit 1
          fi
        shell: bash
      - name: Run Lambda Function Test
        run: |
          python ./src/test/test_lambda_function.py --endpoint $API_ENDPOINT
