name: Setup Environment

on:
  workflow_call:
    outputs:
      S3_BUCKET:
        description: 'S3 Bucket Name'
      S3_KEY_PATH:
        description: 'S3 Key Path'

jobs:
  set_env:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Project Name
        run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Set Workflow Outputs
        id: set_outputs
        run: |
          echo "::set-output name=S3_BUCKET::glpi-bedrock-project-terraform-state"
          echo "::set-output name=S3_KEY_PATH::${PROJECT_NAME}"
