name: Setup Environment

on:
  workflow_call:
    outputs:
      S3_BUCKET:
        description: 'S3 Bucket Name'
      S3_KEY_PATH:
        description: 'S3 Key Path'
      API_GATEWAY_NAME:
        description: 'API Gateway Name'
      API_STAGE_NAME:
        description: 'API Stage Name'

jobs:
  set_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Project Name
        id: extract_project_name
        run: |
          PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Extract Variables from Terraform
        id: extract_vars
        run: |
          API_GATEWAY_NAME=$(terraform output -raw api_gateway_name)
          API_STAGE_NAME=$(terraform output -raw api_stage_name)

          echo "API_GATEWAY_NAME=$API_GATEWAY_NAME" >> $GITHUB_ENV
          echo "API_STAGE_NAME=$API_STAGE_NAME" >> $GITHUB_ENV

      - name: Set Workflow Outputs
        id: set_outputs
        run: |
          echo "S3_BUCKET=glpi-bedrock-project-terraform-state" >> $GITHUB_ENV
          echo "S3_KEY_PATH=${PROJECT_NAME}" >> $GITHUB_ENV

      - name: Output Variables
        run: |
          echo "::set-output name=S3_BUCKET::${{ env.S3_BUCKET }}"
          echo "::set-output name=S3_KEY_PATH::${{ env.S3_KEY_PATH }}"
          echo "::set-output name=API_GATEWAY_NAME::${{ env.API_GATEWAY_NAME }}"
          echo "::set-output name=API_STAGE_NAME::${{ env.API_STAGE_NAME }}"
